/**:
  ros__parameters:
    hdd_reader_port: 7635
    num_disks: 1
    disks: # Until multi type lists are allowed, name N the disks as disk0...disk{N-1}
      disk0:
        name: /dev/sda
        temp_warn: 70.0
        temp_error: 80.0
        free_warn: 100000 #MB
        free_error: 20000 #MB
      disk1:
        name: /dev/sdb
        temp_warn: 70.0
        temp_error: 80.0
        free_warn: 100000 #MB
        free_error: 20000 #MB
